services:
  app:
    build: ./
    volumes:
      - ./data/server:/home/app/data/server
    ports:
      - 9000:9000
    command: sh -c 'npm start'
    depends_on:
      - mongo
    links:
      - mongo
    restart: on-failure
